version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:lts 
    steps:
      - checkout
      - run:
          name: "Install package"
          command: "npm install"
      - run:
          name: "Build project"
          command: "npm run build"

workflows:
  say-hello-workflow:
    jobs:
      - build-and-test
